### ISSUE TITLE
trivial change to make it work with mine

### ISSUE THREAD

**Issue by zenfish** [lum8rjack/C3000Z#1]
For my C300Z I had to change a single line - line 21 in "c3000z_enum.py" - from:

`sout = stdout.decode("utf-8").split("\n")[2]`

To:

`sout = stdout.decode("utf-8")[:-1]`

CenturyLink -

Model Number: C3000Z
Hardware Revision: A0B
Firmware version: CZD005-4.16.011.0

FWIW.  Tnx for putting this out.

**Comment by lum8rjack** [comment]
Sorry for such a late response and thanks for the update! I will test it on my end this week and push the change.

**Comment by micahjon** [comment]
Thanks @zenfish, just confirming that this change worked for me as well

**Comment by micahjon** [comment]
Also, just an FYI that there's now a "Save Configuration" section of "Utilities", so it's no longer under the firmware update section.

**Comment by lum8rjack** [comment]
Thanks for all the updates and details! I updated the decoding statement and added details to the README related to the new configuration area.
