### ISSUE TITLE
OpenSSL Legacy Provider Needs Specifying in Modern OpenSSL Versions

### ISSUE THREAD

**Issue by surewould** [lum8rjack/C3000Z#2]
TY for the research! I was using a newer version of OpenSSL and needed to configure the legacy provider and change the command line options.

Config file changes:
https://github.com/openssl/openssl/blob/master/README-PROVIDERS.md
TL;DR, edit /etc/ssl/openssl.cnf or provide your own config or programmatic settings to openssl and make sure these sections have these values. Mind production with a system wide change. The legacy providers are disabled by default for good reason.
```
openssl_conf = openssl_init

[openssl_init]
providers = provider_sect

[provider_sect]
default = default_sect
legacy = legacy_sect

[default_sect]
activate = 1

[legacy_sect]
activate = 1
```

Original command:
```
openssl des -in <config file> -d -k C1000Z_1234 -a -md md5
```

New command:
```
openssl des -provider legacy -in <config file> -d -k C1000Z_1234 -a -md md5
```

**Comment by lum8rjack** [comment]
Thanks for the additional information! I will add a note in the README with these details to let others know and also get the Dockerfile updated.

**Comment by lum8rjack** [comment]
Thanks again for the details. I went ahead and updated the README with the additional information.
